From 993e2c82c427b14fe5028cb697cef4658d615966 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Micha=C5=82=20G=C3=B3rny?= <mgorny@gentoo.org>
Date: Sat, 16 Mar 2024 09:57:41 +0100
Subject: [PATCH] Fix `test_assert_raises_validation_error` with pytest-8
 (#8995) (#9024)

(cherry picked from commit 22f86ad2ae1df0e1ca33a93275a1dd69d9d50988)
---
 tests/test_validators.py | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/tests/test_validators.py b/tests/test_validators.py
index 5af82373..11e469e2 100644
--- a/tests/test_validators.py
+++ b/tests/test_validators.py
@@ -807,16 +807,16 @@ def test_assert_raises_validation_error():
 
         @validator('a')
         def check_a(cls, v):
-            assert v == 'a', 'invalid a'
+            if v != 'a':
+                raise AssertionError('invalid a')
             return v
 
     Model(a='a')
 
     with pytest.raises(ValidationError) as exc_info:
         Model(a='snap')
-    injected_by_pytest = "\nassert 'snap' == 'a'\n  - a\n  + snap"
     assert exc_info.value.errors() == [
-        {'loc': ('a',), 'msg': f'invalid a{injected_by_pytest}', 'type': 'assertion_error'}
+        {'loc': ('a',), 'msg': 'invalid a', 'type': 'assertion_error'}
     ]
 
 
-- 
2.44.0

