See https://github.com/wbond/oscrypto/issues/80

diff -upr oscrypto-1.3.0.orig/tests/test_tls.py oscrypto-1.3.0/tests/test_tls.py
--- oscrypto-1.3.0.orig/tests/test_tls.py	2024-07-10 15:15:55.074256024 +0200
+++ oscrypto-1.3.0/tests/test_tls.py	2024-07-10 15:19:13.478110756 +0200
@@ -123,6 +123,7 @@ class TLSTests(unittest.TestCase):
                 return
         tls.TLSSocket('global-root-ca-revoked.chain-demos.digicert.com', 443)
 
+    @unittest.skip('broken with OpenSSL 3.0, see https://github.com/wbond/oscrypto/issues/80')
     @connection_timeout()
     def test_tls_error_http(self):
         with assert_exception(self, errors.TLSError, 'server responded using HTTP'):
@@ -214,6 +215,7 @@ class TLSTests(unittest.TestCase):
         with assert_exception(self, errors.TLSVerificationError, 'self-signed'):
             tls.TLSSocket('self-signed.badssl.com', 443)
 
+    @unittest.skip('broken with OpenSSL 3.0, see https://github.com/wbond/oscrypto/issues/80')
     @connection_timeout()
     def test_tls_error_weak_dh_params(self):
         # badssl.com uses SNI, which Windows XP does not support
