Since exceptiongroup is not packaged in Alpine, rewrite test using
native Python 3.11+ syntax.

diff --git a/tests/test_taskgroups.py b/tests/test_taskgroups.py
index 2280b65..3ae6f4b 100644
--- a/tests/test_taskgroups.py
+++ b/tests/test_taskgroups.py
@@ -8,7 +8,6 @@ from collections.abc import AsyncGenerator, Coroutine, Generator
 from typing import Any, NoReturn, cast
 
 import pytest
-from exceptiongroup import catch
 
 import anyio
 from anyio import (
@@ -1304,13 +1303,12 @@ async def test_cancel_before_entering_task_group() -> None:
 
 
 async def test_reraise_cancelled_in_excgroup() -> None:
-    def handler(excgrp: BaseExceptionGroup) -> None:
-        raise
-
     with CancelScope() as scope:
         scope.cancel()
-        with catch({get_cancelled_exc_class(): handler}):
+        try:
             await anyio.sleep_forever()
+        except* get_cancelled_exc_class():
+            raise
 
 
 async def test_cancel_child_task_when_host_is_shielded() -> None:
