Patch-Source: https://github.com/matrix-org/pantalaimon/commit/807deb94ee9e39bb570a904960d750e8d0dd5086.patch
--
From 807deb94ee9e39bb570a904960d750e8d0dd5086 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Gerber=20L=C3=B3r=C3=A1nt=20Viktor?= <glorantq@gmail.com>
Date: Fri, 3 Feb 2023 05:45:50 +0100
Subject: [PATCH] fix media

---
 pantalaimon/daemon.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/pantalaimon/daemon.py b/pantalaimon/daemon.py
index 3264cab..c5e4ac4 100755
--- a/pantalaimon/daemon.py
+++ b/pantalaimon/daemon.py
@@ -1273,7 +1273,7 @@ async def _load_decrypted_file(self, server_name, media_id, file_name):
         client = next(iter(self.pan_clients.values()))
 
         try:
-            response = await client.download(server_name, media_id, file_name)
+            response = await client.download(server_name=server_name, media_id=media_id, filename=file_name)
         except ClientConnectionError as e:
             raise e
 
